[env]
TERM = "xterm-256color"

[scrolling]
history = 100000

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 12.0
offset = { y = 2 }

[window]
padding = { x = 8, y = 8 }
dynamic_padding = false
decorations = "full"

# Window title
title = "Alacritty"

# # Window class (Linux/BSD only):
# [window.class]
# instance = "Alacritty"
# general = "Alacritty"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"] 


# Colors (Gruvbox dark)
[colors]
  # Default colors
  [colors.primary]
  background = "0x282828"
  foreground = "0xebdbb2"

  # Normal colors
  [colors.normal]
  black = "0x282828"
  red = "0xcc241d"
  green = "0x98971a"
  yellow = "0xd79921"
  blue = "0x458588"
  magenta = "0xb16286"
  cyan = "0x689d6a"
  white = "0xa89984"

  # Bright colors
  [colors.bright]
  black = "0x928374"
  red = "0xfb4934"
  green = "0xb8bb26"
  yellow = "0xfabd2f"
  blue = "0x83a598"
  magenta = "0xd3869b"
  cyan = "0x8ec07c"
  white = "0xebdbb2"